### ISSUE TITLE
Final style improvements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#264]
Based on feedback from Steel, Leigh, Hugh, Travis

## CSS changes
- [x] Hyperlinks should mimic hyperlink styling on marketing site (no underline and in red HEX BB2026)
- [x] CTA text - "Learn more about Pressbooks"
- [x] The font in the marketing text is too large
- [x] Use white background for the introductory text, followed by the light blue behind the books (as in the original flat designs)
- [x] the filters and find a book space is a little off. eg. the filters should probably be more in line with the book cover, and the page numbers are sort of floating. I prefer the organization and the boxed 'find a book' feature in the original flat designs.
- [x] Make the words "self-guided tour" a hyperlink in the welcome text instead of directing people to the top nav bar
- [x] Enforce uniform size (max-height with overflow hidden) for featured images for collections https://github.com/pressbooks/pressbooks-book-directory-fe/issues/270
- [x] Add rounded edges to feature collection covers (border-radius: 4px) as in staging directory
- [x] Make decision about display of featured collections on mobile/tablets
- [x] Fix footer padding

## Structural changes
- [x] Add elements from the marketing site's footer in the footer of the Directory
- [x] Add read more button/option to truncated descriptions: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/285

## To be handled separately
- [ ] Improve handling of cover images (load smaller resolution images): https://github.com/pressbooks/pressbooks-book-directory-fe/issues/269
- [ ] Move icons on the book cards to the left of card (run across whole bottom of card, instead of just under the book cover) https://github.com/pressbooks/pressbooks-book-directory-fe/issues/303

**Comment by hughmcguire** [comment]
A handful more comments (almost all of which I would not expect to be addressed in this round): 

1/ Filters:
Maybe not  for this round of improvements? but: these filters are overwhelming, both the number of filters and when you click on a filter say SUBJECT, and have a dropdown of 10 Subjects with “780 more” … I don’t think we’g got our UX right.

Ditto with Networks etc

A simplified Filter sidebar with the ability to open an Advanced Filters window, with better UX for this vast array of toggles, would make more sense. (Probably not for this release though)

(Question: are we planning to do any analysis of 
how users are using the Directory? eg with heatmaps or another tool?)

2/ cover images
would be nice if we could standardize the output size

3/ footer should be the same as the marketing site footer (this one *should* be included in this round) 

4/ expanded card view: 

4a/ when the book description is truncated, I expect an easy route to see more: an expand button to show me the whole thing (better), or a link to the book (probably not ideal). 

4.b/ Even better would be to have the TOC included in the “expanded” card view

**Comment by SteelWagstaff** [comment]
Thanks @hughmcguire 

1/ re: subjects, we're planning the following: 
> Flatten Thema taxonomy to a two-level structure including first and second levels. This will keep the list short and manageable when the facet is opened and the subjects have not been expanded. The facet search function should still function for third and fourth levels, even though they are invisible (e.g., a search for third-level subject Television will produce its second-level parent, Performing Arts).

Doing this requires some significant changes to our API, however. See https://github.com/pressbooks/bi-data-manager/issues/290 as the blocker. 

We have done some analysis of how users use Directory, but would like to do more following v2 release.

2/ We will be working on cover images. See https://github.com/pressbooks/pressbooks-book-directory-fe/issues/269 & https://github.com/pressbooks/pressbooks-book-directory-fe/issues/270. This may also require some changes to the API, but I'm hopeful we can make some improvements soon.

3/ This will be done before end of the coming week and will be included in v2

4a/ We used to display the whole book description on the card, but it got unwieldy so we truncated it. https://github.com/pressbooks/pressbooks-book-directory-fe/pull/83#issuecomment-672300096 We plan to add a “read more” link to expand descriptions that have been cut off. This will provide a better experience as users won’t have to leave the search results to learn what a book is about. 

4b/ ToC display or even full text search, while cool, will be unattainable without significant changes to API and Algolia data model.
