### ISSUE TITLE
[Research] - Reduce Algolia transactions during E2E tests

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-book-directory-fe#288]
Currently the E2E tests are consuming a large part of the Algolia's quota operations. Scope for now for this task is Part 1 and Part 2.

## Part 1
- [x] Os create an export of the E2E text index via API & share with each individual dev
- [x] Individual devs create an import of this index into their own personal free apps and create replicas needed for testing
- [x] Devs reference this app and index when working locally

## Part 2
- [x] Steel email Algolia and ask for more operations on our open source plan and for pricing options if they say no
 
## Part 3 [later]
- [x] Research approaches to mocking the index so that it doesn't consume as many operations

Research how to reduce the quota operations. There are 2 links I found quickly (probably there are more solutions and alternatives):
- https://www.algolia.com/doc/api-client/advanced/configure-the-client/javascript/?client=javascript 
- https://github.com/davesag/mock-algolia
